# Generated by Django 5.1.2 on 2025-07-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitedashboard', '0032_heroslider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='heading',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about_us/,'),
        ),
    ]
