# Generated by Django 5.1.2 on 2025-07-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0010_bookingdetail_security_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetail',
            name='service_type',
            field=models.CharField(choices=[('Only-Slot-Booking', 'Only Slot Booking'), ('Only-Normal-Process', 'Only Normal Process'), ('Express-Dates', 'Express Dates'), ('Full-Process-Dates', 'Full Process & Dates'), ('Full-Process-Express-Dates', 'Full Process & Express Dates')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='bookingdetail',
            name='appointment_location',
            field=models.CharField(choices=[('Pan-India', 'Pan India'), ('Chennai-Only', 'Chennai Only'), ('Mumbai-Both-Dates', 'Mumbai-(Both Dates'), ('Mumbai-Delhi-Hydrabad-Chennai-Kolkata', 'Mumbai, Delhi, Hydrabad, Chennai, Kolkata'), ('Mumbai/Location-of-Your-Choice', 'Mumbai/Location of Your Choice'), ('Location-of-your-choice/Hydrabad-Chennai', 'Location of your Choice/Hydrabad or Chennai')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bookingdetail',
            name='visa_type',
            field=models.CharField(choices=[('B1B2-Visa', 'B1B2 Visa'), ('B1B2-Visa Dropbox', 'B1B2 Visa Dropbox'), ('C1d-Visa', 'C1d- fresh or Dropbox'), ('H1b/H4-Visa', 'H1b/H4- Fresh or Dropbox'), ('F1/F2-Visa', 'F1/F2- fresh or dropbox'), ('L1/L2-Visa', 'L1/L2- Fresh or Dropbox'), ('Blanket-L1-Visa', 'Blanket L1 Visa'), ('Blanket-L2-Visa-Drop-visa', 'Blanket L2 Visa Drop/Fresh'), ('Immigration-Visa', 'Immigration Visa Any category')], max_length=50),
        ),
    ]
