# Generated by Django 5.1.2 on 2025-07-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0011_bookingdetail_service_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetail',
            name='service_type',
            field=models.CharField(choices=[('Only-Slot-Booking', 'Only Slot Booking'), ('Only-Normal-Process', 'Only Normal Process'), ('Express-Dates', 'Express Dates'), ('Full-Process-Dates', 'Full Process & Dates'), ('Full-Process-Express-Dates', 'Full Process & Express Dates')], max_length=50),
        ),
    ]
